theme: jekyll-theme-minimal
markdown: kramdown
title: Juan Manuel Campanario
logo: "IMG-4228.JPG"
description: 
   Hi! I'm Juan. [resume](/juan_resume_webversion.pdf)
   <br><br>
   <a href="https://drive.google.com/file/d/101-MH1rQbIDYm2vc6HUfBBTqI_4n1BQf/view?usp=sharing" target="_blank">Resume</a> | 
   <a href="mailto:juan.m.campanario@gmail.com">Email</a> | 
   <a href="https://www.linkedin.com/in/juanmcampanario" target="_blank">Linkedin</a>
