theme: jekyll-theme-minimal
markdown: kramdown
google_analytics: UA-310372936
title: Juan Manuel Campanario
logo: "pitt2020_schoolphoto.jpg"
description: 
   Hi! I'm Juan.
   <br><br>
   <a href="https://drive.google.com/file/d/1MLIXSXO__mb5KlWbeVUifiBmb0y71OLJ/view?usp=sharing" target="_blank">Resume</a> | 
   <a href="mailto:juan.m.campanario@gmail.com">Email</a> | 
   <a href="https://www.linkedin.com/in/juanmcampanario" target="_blank">Linkedin</a> |
   <a href="https://twitter.com/jmcampanario" target="_blank">Twitter</a> 

# About Me
I am a PhD candidate at the University of Pittsburgh. I am passionate about quantitative analysis, with a specific interest in causal and reduced form work. My dissertation focuses on health and economic development. I also have some short-lived assignments on tax assessments, education, and housing vouchers, some of which is featured in the abandoned projects section. Aside from projects, I like to stay active. I played tennis, mainly doubles, in high school and still play on occassion. I've moved to more solo activities during graduate school, such as lifting and [running](https://www.strava.com/athletes/34312248){:target="_blank"}.
