theme: jekyll-theme-minimal
markdown: kramdown
google_analytics: UA-310372936
title: Juan Manuel Campanario
logo: "pitt2020_schoolphoto.jpg"
description: 
   Hi! I'm Juan.
   <br><br>
   <a href="https://drive.google.com/file/d/1MLIXSXO__mb5KlWbeVUifiBmb0y71OLJ/view?usp=sharing" target="_blank">Resume</a> | 
   <a href="mailto:juan.m.campanario@gmail.com">Email</a> | 
   <a href="https://www.linkedin.com/in/juanmcampanario" target="_blank">Linkedin</a> |
   <a href="https://twitter.com/jmcampanario" target="_blank">Twitter</a> 
