theme: jekyll-theme-minimal
markdown: kramdown
google_analytics: UA-310372936
title: Juan Manuel Campanario
logo: "pictures/IMG-4228.JPG"
description: 
   Hi! I'm Juan.
   <br><br>
   <a href="https://drive.google.com/file/d/1KWtaCcV9D6g1Y366rY0EdlhnfmXHHqGa/view?usp=drive_link" target="_blank">CV</a> | 
   <a href="mailto:juan.m.campanario@gmail.com">Email</a> | 
   <a href="https://www.linkedin.com/in/juanmcampanario" target="_blank">Linkedin</a> |
   <a href="https://twitter.com/jmcampanario" target="_blank">Twitter</a> 
