theme: jekyll-theme-minimal
title: Juan Manuel Campanario
logo: "IMG-4228.JPG"
description: Hi! I'm Juan, PhD student at the University of Pittsburgh. 
   <br><br>
   <a href="www.linkedin.com/in/juanmcampanario">
