theme: jekyll-theme-minimal
markdown: kramdown
google_analytics: G-Q91MKWFJ5G
title: Juan Manuel Campanario
logo: "IMG-4228.JPG"
description: 
   Hi! I'm Juan.
   <br><br>
   <a href="https://drive.google.com/file/d/1MLIXSXO__mb5KlWbeVUifiBmb0y71OLJ/view?usp=sharing" target="_blank">Resume</a> | 
   <a href="mailto:juan.m.campanario@gmail.com">Email</a> | 
   <a href="https://www.linkedin.com/in/juanmcampanario" target="_blank">Linkedin</a> |
   <a href="https://twitter.com/jmcampanario" target="_blank">Twitter</a> 
